version: '3.7'
services:
        todo-web-application:
                image: marcehm/todo-web-application-mysql:0.0.1-SNAPSHOT
                ports:
                        - "8080:8080"
                restart: always
                depends_on:
                        - mysql
                environment: 
                        RDS_HOSTNAME: mysql
                        RDS_PORT: 3306
                        RDS_DB_NAME: todos
                        RDS_USERNAME: todos-user
                        RDS_PASSWORD: dummytodos
        mysql:
                image: mysql:5.7
                volumes:
                        - type: volume
                          source: mysql_data
                          target: /var/lib/mysql
                networks:
                        - spring-boot-mysql-network
                ports:
                        - "3306:3306"
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: dummypassword
                        MYSQL_USER: todos-user
                        MYSQL_PASSWORD: dummytodos
                        MYSQL_DATABASE: todos
volumes:
        mysql_data: {}
networks:
        spring-boot-mysql-network:
                driver: bridge
